firstname = input('What is your name? ')
print( 'Hello '+ firstname + ', my name is chatbot.')
age = input('How old are you? ')
print( 'WoW, '+ age + ' years old! I was born today.' )
feeling = input('How are you feeling today? ')
print('Glad to hear your feeling ' + feeling .lower() + ' .That is wonderful to hear. '  )